config/routes.rb
Rails.application.routes.draw do
  root "docs#index"

  resources :docs do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comments.rb
class Commnet < ApplicationRecord
  belongs_to :doc
end

app/models/doc.rb
class Doc < ApplicationRecord
    has_many :comments
    
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @doc = Doc.find(params[:doc_id])
        @comment = @doc.comments.create(comment_params)
        redirect_to doc_path(@doc)
    end
    
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def index
    @docs = Doc.all
  end

  def show
    @doc = Doc.find(params[:id])
  end

  def new
    @doc = Doc.new
  end

  def create
    @doc = Doc.new(doc_params)
    if @doc.save
      redirect_to @doc
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @doc = Doc.find(params[:id])
  end

  def update
    @doc = Doc.find(params[:id])
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def doc_params
    params.require(:doc).permit(:title, :body)
  end

  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/comments/_form.html.erb
<%= form_with model: [ @doc, @doc.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/docs/_form.html.erb
<%= form_with model: doc do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% doc.errors.full_messages_for(:title).each do |message| %>
     <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% doc.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>  
    <% end %>
  </div>    

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Edit Doc</h1>

<%= render "form", doc: @doc %>

app/views/docs/index.html.erb
<h1>Document title below with link!</h1>

<ul>
  <% @docs.each do |doc| %>
    <li>
      <%= link_to doc.title, doc %>
    </li>
  <% end %>
</ul>
<%= link_to "Create new", new_doc_path %>

app/views/docs/new.html.erb
<h1>New doc</h1>
<%= render "form", doc: @doc %>

app/views/docs/show.html.erb
<h1><%= @doc.title %></h1>

<p><%= @doc.body %></p>
<ul>
  <li><%= link_to "Edit", edit_doc_path(@doc) %></li>
  <li><%= button_to "Delete", doc_path(@doc),method: :delete, data: { turbo: false } %>
                  </li>
</ul>

<h2>Comments</h2>
<%= render @doc.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://127.0.0.1:3000/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://127.0.0.1:3000/docs/1">Climate</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://127.0.0.1:3000/docs/2">Heat wave</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://127.0.0.1:3000/docs/6">World</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>